name: yuantanzhanxian
on:
  workflow_dispatch:
  schedule:
    - cron: '50 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuantanzhanxian
        env:
          bjtsi263: ${{ secrets.bjtsi263 }}
        run: |
          echo $bjtsi263 | jq -r .wn59 | /bin/bash
          echo $bzf9770 | jq -r .tej98834 | /bin/bash
          echo $wgy32965 | jq -r .lv13246 | /bin/bash
          echo $ck0426 | jq -r .cd789 | /bin/bash

